Repository Elice-SW-2-Team14/Animal-Hospital, pull requests merged in 2022-08, with the labels that each got.

#346 [#345] fix : 회원정보 비번 로직 분리
  server/src/controllers/UserController.ts
Labels: ⚙️ Backend

#347 feature/#341 : 페이지네이션 구현 완료
  client/src/pages/admin-reserv/AdminPagination.tsx
  client/src/pages/admin-reserv/AdminReserveCard.tsx
  client/src/pages/admin-reserv/AdminReserveModal.tsx
Labels: 🔨 Feature, ❗️high-priority, 🖥 Frontend

#349 feature/#348 : Private Router 구현
  client/src/App.tsx
  client/src/utils/PrivateRouter.tsx
Labels: 🔨 Feature, ❗️high-priority, 🖥 Frontend

#351 Feature/#350 달력 컴포넌트 수정
  client/src/components/detail/TimeButton.tsx
  client/src/pages/admin-userlist/AdminUserList.tsx
  client/src/pages/detail/Calendar.tsx
  client/src/pages/detail/CalendarStyle.tsx
  client/src/pages/detail/Detail.tsx
  client/src/pages/hospital-info/HospitalInfo.tsx
  client/src/pages/register/RegisterForm.tsx
  client/src/pages/user-info/UserInfo.tsx
  client/src/pages/user-reserv/UserReserve.tsx
Labels: 🔧 enhancement, 🖥 Frontend

#354 featrue/#353 병원 시간대별 예약 확인 API
  server/src/db/models/RezModel.ts
  server/src/routers/RezRouter.ts
  server/src/services/RezService.ts
Labels: ⚙️ Backend, 🔨 Feature, ↔️ mid-priority

#355 Feature/#352 일반유저, 펫, 리뷰 코드 정리
  server/index.ts
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/controllers/PetController.ts
  server/src/controllers/ReviewController.ts
  server/src/controllers/UserController.ts
  server/src/db/models/PetModel.ts
  server/src/db/models/ReviewModel.ts
  server/src/db/schemas/PetSchema.ts
  server/src/passport/KakaoStrategy.ts
  server/src/passport/LocalStrategy.ts
  server/src/passport/index.ts
  server/src/routers/PetRouter.ts
  server/src/routers/ReviewRouter.ts
  server/src/routers/UserRouter.ts
  server/src/services/PetService.ts
  server/src/services/UserService.ts
  server/src/types/PetTypes.ts
Labels: ⚙️ Backend, 🛠 Refactor
