Repository Elice-SW-2-Team14/Animal-Hospital, pull requests merged in 2022-07, with the labels that each got.

#20 feature#19 서버 폴더 구조 생성
  server/src/.gitkeep
  server/src/db/index.ts
  server/src/db/models/.gitkeep
  server/src/db/schemas/.gitkeep
  server/src/middlewares/index.ts
  server/src/routers/index.ts
  server/src/service/index.ts
Labels: ⚙️ Backend, 🔩 setup, ❗️high-priority

#21 feature/#17 : 프론트엔드 폴더 구조 생성
  client/.gitignore
  client/.gitkeep
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.tsx
  client/src/index.tsx
  client/tsconfig.json
Labels: 🔩 setup, ❗️high-priority, 🖥 Frontend

#23 feature/#17: assets 폴더 추가
  client/src/assets/.gitkeep
  client/src/components/.gitkeep
  client/src/components/common/.gitkeep
  client/src/hooks/.gitkeep
  client/src/pages/.gitkeep
  client/src/store/.gitkeep
  client/src/styles/.gitkeep
  client/src/utils/.gitkeep
Labels: 🔩 setup, ❗️high-priority, 🖥 Frontend

#25 Feature/#22 서버 기본 세팅
  .gitignore
  server/index.ts
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/tsconfig.json
  server/types/express/index.d.ts
Labels: ⚙️ Backend, 🔩 setup, ❗️high-priority

#14 feature/#12: test 파일 생성
  client/test.tsx
Labels: ⬇️ low-priority, 🖥 Frontend

#27 feature/#24: 전역스타일 설정 및 모듈 설치
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/index.tsx
  client/src/styles/Colors.tsx
  client/src/styles/GlobalStyles.tsx
Labels: 🔩 setup, 🔨 Feature, ❗️high-priority, 🖥 Frontend

#28 feature/#26 필요한 패키지 추가
  server/package-lock.json
  server/package.json
Labels: ⚙️ Backend, 🔩 setup, ❗️high-priority

#32 [#31]feat: DefaultTheme palette 자동완성 기능 추가
  client/package-lock.json
  client/src/styles/.gitkeep
  client/src/styles/style.d.ts
  client/test.tsx
Labels: 🔩 setup, ❗️high-priority, 🖥 Frontend

#40 Feature/#36: userinfo 폴더 생성, 디자인 틀 완성
  client/src/components/user-info/UserInfo.tsx
Labels: 🖥 Frontend

#41 Feature/#39: 유저 마이페이지 폴더 생성, 디자인 틀 완성
  client/src/components/user-mypage/UserMypage.tsx
  client/src/index.tsx
  package-lock.json
  package.json
Labels: 🖥 Frontend

#43 feature/#33 : 로그인 기본 디자인 완성
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/login/LoginLayout.tsx
  client/src/components/login/LoginStyle.tsx
Labels: 🔨 Feature, ❗️high-priority, 🖥 Frontend

#45 Feature/#44: 어드민 마이페이지 폴더 생성, 디자인 틀 완성
  client/src/components/admin-mypage/AdminMypage.tsx
  client/src/components/user-mypage/UserMypage.tsx
Labels: 🖥 Frontend

#42 feature/#37: pet-info 폴더 생성, 디자인 틀 생성
  client/src/pages/pet-info/PetInfo.tsx
Labels: 🔨 Feature, 🖥 Frontend

#47 Feature/#34: 일반 회원가입 디자인 완성
  client/src/components/.gitkeep
  client/src/components/NRegisterForm.tsx
  client/src/components/common/.gitkeep
  client/src/components/common/Title.tsx
  client/src/pages/.gitkeep
  client/src/pages/Register.tsx
Labels: ❗️high-priority, 🖥 Frontend

#50 feature/#49 오류처리 구현
  server/src/app.ts
  server/src/middlewares/ErrorHandler.ts
  server/src/middlewares/ErrorLogger.ts
  server/src/middlewares/index.ts
Labels: ⚙️ Backend, 🔨 Feature, ❗️high-priority

#55 Feature/#54: 내 병원 페이지 폴더 생성, 디자인 틀 완성
  client/src/pages/hospital-info/HospitalInfo.tsx
Labels: ❗️high-priority, 🖥 Frontend

#60 Feature/#56: 회원 개인정보 페이지 디자인 작업 리팩토링
  client/src/components/InfoForm.tsx
  client/src/pages/user-info/UserInfo.tsx
Labels: 🖥 Frontend

#53 feature/#52: .env파일 생성 후 gitignore에 추가
  client/.gitignore
  client/package-lock.json
  client/package.json
Labels: 🔩 setup, 🔨 Feature

#68 feature/#65: 스키마 구현
  server/src/db/schemas/.gitkeep
  server/src/db/schemas/HospRegStatusSchema.ts
  server/src/db/schemas/HospSchema.ts
  server/src/db/schemas/HospServiceSchema.ts
  server/src/db/schemas/HospStatusSchema.ts
  server/src/db/schemas/HospTagSchema.ts
Labels: ⚙️ Backend, 🔨 Feature, ❗️high-priority

#73 feature/#64 : 로그인 validation 기본틀 완성
  client/package-lock.json
  client/package.json
  client/src/pages/login/LoginLayout.tsx
  client/src/pages/login/LoginStyle.tsx
Labels: 🔨 Feature, ❗️high-priority, 🖥 Frontend

#75 feature/#69 병원상태 API 구현
  server/src/.eslintrc
  server/src/.gitkeep
  server/src/.prettierrc
  server/src/app.ts
  server/src/db/index.ts
  server/src/db/models/HospStatusModel.ts
  server/src/routers/HospStatusRouter.ts
  server/src/routers/index.ts
  server/src/service/index.ts
  server/src/services/HospStatusService.ts
  server/src/services/index.ts
Labels: ⚙️ Backend, 🔨 Feature, ❗️high-priority

#88 [#87]feature: Router 설정
  client/src/App.tsx
Labels: 🔩 setup, ❗️high-priority, 🖥 Frontend

#77 Feature/#62: 기초 API 구현 전 펫 CRUD
  client/src/pages/pet-info/PetInfo.tsx
Labels: 🔨 Feature, ❗️high-priority, 🖥 Frontend

#70 Feature/#61 일반회원가입 api 작성 및 postman 문서 작성
  server/index.ts
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/db/index.ts
  server/src/db/models/UserModel.ts
  server/src/db/schemas/UserSchema.ts
  server/src/routers/UserRouter.ts
  server/src/routers/index.ts
  server/src/service/UserService.ts
  server/src/service/index.ts
Labels: ⚙️ Backend, 🔨 Feature, ❗️high-priority

#82 feature/#81 병원태그 API 구현
  server/src/app.ts
  server/src/db/index.ts
  server/src/db/models/HospTagModel.ts
  server/src/routers/HospTagRouter.ts
  server/src/routers/index.ts
  server/src/services/HospTagService.ts
  server/src/services/index.ts
Labels: ⚙️ Backend, 🔨 Feature, ❗️high-priority

#84 Feature/#59: 회원가입 validation 설정
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/pages/register/Postcode.tsx
  client/src/pages/register/Register.tsx
  client/src/pages/register/RegisterForm.tsx
  client/src/pages/register/Title.tsx
  client/src/styles/Colors.tsx
  client/src/styles/style.d.ts
Labels: 🔨 Feature, ❗️high-priority, 🖥 Frontend

#92 Feature/#91
  server/src/db/schemas/HospSchema.ts
  server/src/routers/HospRegStatusRouter.ts
  server/src/routers/HospStatusRouter.ts
  server/src/routers/HospTagRouter.ts
Labels: 🐛 Bug, ⚙️ Backend, ❗️high-priority

#94 feature/#91: 병원 회원가입 구현
  server/src/app.ts
  server/src/db/index.ts
  server/src/db/models/HospModel.ts
  server/src/db/models/HospRegStatusModel.ts
  server/src/db/schemas/HospSchema.ts
  server/src/routers/HospRouter.ts
  server/src/routers/index.ts
  server/src/services/HospService.ts
  server/src/services/index.ts
Labels: ⚙️ Backend, 🔨 Feature, ❗️high-priority

#93 Feature/#80 일반회원정보 조회 및 수정 api
  server/src/db/models/UserModel.ts
  server/src/middlewares/LoginRequired.ts
  server/src/routers/UserRouter.ts
  server/src/service/UserService.ts
  server/src/service/index.ts
  server/src/services/UserService.ts
  server/src/services/index.ts
  server/src/types/express/index.d.ts
  server/tsconfig.json
  server/types/express/index.d.ts
Labels: ⚙️ Backend, 🔨 Feature, ❗️high-priority

#100 feature/#97: 병원 로그인 구현
  server/src/db/models/HospModel.ts
  server/src/routers/HospRouter.ts
  server/src/services/HospService.ts
Labels: ⚙️ Backend, 🔨 Feature, ❗️high-priority

#98 feature/#89: 회원가입 API 연동 후 토큰을 로컬스토리지에 저장
  client/package-lock.json
  client/src/pages/login/LoginLayout.tsx
  client/src/pages/login/LoginStyle.tsx
Labels: 🔨 Feature, ❗️high-priority, 🖥 Frontend

#101 feature/#97 client에 role전달 추가
  server/src/routers/HospRouter.ts
Labels: ⚙️ Backend, 🔧 enhancement, ↔️ mid-priority

#99 Feature/#90: 병원 스키마 적용, 폼 저장 시 데이터 생성
  client/src/pages/hospital-info/HospitalInfo.tsx
Labels: 🔨 Feature, ❗️high-priority, 🖥 Frontend

#107 feature/#86: 회원가입 API 완성
  client/package-lock.json
  client/src/components/RegExp.ts
  client/src/pages/register/Postcode.tsx
  client/src/pages/register/RegisterForm.tsx
  client/src/pages/register/Title.tsx
Labels: 🔨 Feature, ❗️high-priority, 🖥 Frontend

#114 Feature/#102
  client/package-lock.json
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/db/index.ts
  server/src/db/models/PetModel.ts
  server/src/db/schemas/PetSchema.ts
  server/src/db/schemas/UserSchema.ts
  server/src/routers/PetRouter.ts
  server/src/routers/UserRouter.ts
  server/src/routers/index.ts
  server/src/services/PetService.ts
  server/src/services/UserService.ts~Stashed changes
Labels: ⚙️ Backend, 🔨 Feature, ❗️high-priority

#118 Feature/#105 회원 정보 조회, 충돌 해결
  client/package-lock.json
  client/src/components/DaumPost.tsx
  client/src/components/ModalStyle.tsx
  client/src/pages/user-info/Interface.tsx
  client/src/pages/user-info/UserInfo.tsx
  server/src/app.ts
Labels: 🖥 Frontend

#116 Feature/#115 S3 설정을 통해 병원 정보에 사진을 추가
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/routers/HospRouter.ts
  server/src/utils/S3.ts
  server/src/utils/index.ts
Labels: ⚙️ Backend, 🔧 enhancement, 🔨 Feature, ❗️high-priority

#126 Feature/#123 병원 삭제 API구현
  package-lock.json
  package.json
  server/src/middlewares/HospLoginRequired.ts
  server/src/middlewares/index.ts
  server/src/routers/HospRouter.ts
Labels: ⚙️ Backend, 🔨 Feature, ❗️high-priority

#133 Feature/#103 병원 정보 페이지 키워드 기능 추가
  client/src/pages/hospital-info/HospitalInfo.tsx
Labels: 🔨 Feature, ❗️high-priority, 🖥 Frontend

#143 [#142]refactor:영업 시간 수정
  client/src/pages/hospital-info/HospitalInfo.tsx
Labels: 🛠 Refactor, ↔️ mid-priority, 🖥 Frontend

#127 feature/#125 관리자의 전체 회원정보 조회 api 작성
  server/package-lock.json
  server/package.json
  server/src/db/models/UserModel.ts
  server/src/middlewares/AdminRequired.ts
  server/src/routers/UserRouter.ts
  server/src/services/UserService.ts
Labels: ⚙️ Backend, 🔨 Feature, ❗️high-priority

#131 Feature/#128 비밀번호검증로직 추가
  server/package-lock.json
  server/package.json
  server/src/db/models/UserModel.ts
  server/src/middlewares/AdminRequired.ts
  server/src/routers/UserRouter.ts
  server/src/services/UserService.ts
Labels: ⚙️ Backend, ❗️high-priority

#146 feature/#137 상세페이지 디자인 틀 구현
  client/src/App.tsx
  client/src/pages/detail/Calendar.tsx
  client/src/pages/detail/Detail.tsx
Labels: 🖥 Frontend

#138 Feature/#132 회원탈퇴 api
  server/src/db/models/UserModel.ts
  server/src/db/schemas/UserSchema.ts
  server/src/middlewares/AdminRequired.ts
  server/src/middlewares/CheckStatusRequired.ts
  server/src/middlewares/LoginRequired.ts
  server/src/middlewares/index.ts
  server/src/routers/UserRouter.ts
  server/src/services/UserService.ts
  server/src/types/express/index.d.ts
Labels: ⚙️ Backend, 🔨 Feature, ❗️high-priority

#144 feature/#108: Header Footer 디자인 & 기능 추가
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Footer.tsx
  client/src/components/Header.tsx
  client/src/components/Search.tsx
  client/src/pages/home/Home.tsx
  client/src/pages/register/RegisterForm.tsx
  client/src/styles/GlobalStyles.tsx
Labels: 🔨 Feature, ❗️high-priority, 🖥 Frontend

#139 feature/#117 : 메인 카드뷰 컴포넌트 작업
  client/package.json
  client/public/sample.jpg
  client/src/components/main/MainCard.tsx
  client/src/components/main/MainCardStyle.tsx
  client/src/components/main/MainData.tsx
  client/src/components/main/MainKeyWord.tsx
  client/src/components/main/MainKeyWordStyle.tsx
Labels: 🔨 Feature, ❗️high-priority, 🖥 Frontend

#141 feature/#135: 병원 서비스 API 구현
  server/src/db/index.ts
  server/src/db/models/HospModel.ts
  server/src/db/models/HospServiceModel.ts
  server/src/db/schemas/HospServiceSchema.ts
  server/src/middlewares/HospLoginRequired.ts
  server/src/middlewares/OnlyHospOwner.ts
  server/src/middlewares/index.ts
  server/src/routers/HospRouter.ts
  server/src/services/HospService.ts
  server/src/services/HospServiceService.ts
  server/src/services/index.ts
  server/src/types/express/index.d.ts
Labels: ⚙️ Backend, 🔧 enhancement, 🔨 Feature, ❗️high-priority

#136 Feature/#96 관리자 전체 회원 리스트 디자인
  client/src/App.tsx
  client/src/pages/admin-list/AdminList.tsx
  client/src/pages/admin-list/HpCard.tsx
  client/src/pages/admin-list/UserCard.tsx
  client/src/pages/admin-list/style.tsx
Labels: 🖥 Frontend

#150 Feature/#149 태그 이미지 추가 및 병원 이미지 여러개 추가
  server/src/db/models/HospModel.ts
  server/src/db/schemas/HospSchema.ts
  server/src/routers/HospRouter.ts
  server/src/routers/HospTagRouter.ts
Labels: ⚙️ Backend, 🔧 enhancement, 🔨 Feature, ↔️ mid-priority

#157 Feature/#140 병원 정보 페이지 서비스 기능 추가
  client/src/pages/hospital-info/HospitalInfo.tsx
  client/src/pages/hospital-info/Interface.tsx
  client/src/pages/hospital-info/Style.tsx
Labels: 🛠 Refactor, 🔨 Feature, ❓Question, 🖥 Frontend

#158 Feature/#153: 관리자 전체 회원 정보 불러오기
  client/package-lock.json
  client/src/App.tsx
  client/src/components/Liststyle.tsx
  client/src/pages/admin-hplist/AdminHospitalList.tsx
  client/src/pages/admin-hplist/HpCard.tsx
  client/src/pages/admin-list/AdminList.tsx
  client/src/pages/admin-list/UserCard.tsx
  client/src/pages/admin-mypage/AdminMypage.tsx
  client/src/pages/admin-userlist/AdminUserList.tsx
  client/src/pages/admin-userlist/UserCard.tsx
  client/src/pages/hospital-mypage/HospitalMypage.tsx
  client/src/pages/user-info/UserInfo.tsx
  client/src/pages/user-mypage/UserMypage.tsx
Labels: 🖥 Frontend

#154 Feature/#148 펫 정보 등록, 수정시 이미지 업로드 기능 추가
  server/src/routers/PetRouter.ts
Labels: ⚙️ Backend, 🔨 Feature, ❗️high-priority

#162 Feature/#160 회원탈퇴 미들웨어 삭제 후 로그인 로직으로 통합
  server/src/app.ts
  server/src/db/models/UserModel.ts
  server/src/middlewares/CheckStatusRequired.ts
  server/src/middlewares/LoginRequired.ts
  server/src/middlewares/index.ts
  server/src/routers/PetRouter.ts
  server/src/routers/UserRouter.ts
  server/src/services/UserService.ts
  server/src/services/index.ts
Labels: ⚙️ Backend, 🔧 enhancement

#161 Feature/#155 병원 회원가입 한 후 상태 변경 수정
  server/src/db/models/HospModel.ts
  server/src/db/schemas/HospSchema.ts
  server/src/routers/HospRouter.ts
  server/src/services/HospService.ts
Labels: ⚙️ Backend, 🔧 enhancement, 🔨 Feature, ❗️high-priority

#164 Feature/#163 오피스아워 피드백
  client/src/pages/admin-userlist/AdminUserList.tsx
  client/src/pages/user-info/Interface.tsx
  client/src/pages/user-info/UserInfo.tsx
Labels: 🖥 Frontend

#167 feature/#166 병원 디테일 페이지 API 구현
  server/src/routers/HospRouter.ts
Labels: ⚙️ Backend, 🔨 Feature, ❗️high-priority

#169 feature/#168: 예약하기 컴포넌트 완성
  client/package.json
  client/src/components/TimeButton.tsx
  client/src/pages/detail/Calendar.tsx
  client/src/pages/detail/Detail.tsx
Labels: 🔨 Feature, ❗️high-priority, 🖥 Frontend

#172 feature/#165 펫 정보 디자인 틀 재구성
  client/src/App.tsx
  client/src/pages/pet-information/AddPet.tsx
  client/src/pages/pet-information/PetCard.tsx
  client/src/pages/pet-information/PetInfoStyle.tsx
  client/src/pages/pet-information/PetInformation.tsx
Labels: 🖥 Frontend

#180 feature/#145: 태그 디자인 & 기능
  client/src/App.tsx
  client/src/components/Footer.tsx
  client/src/components/HeaderMypage.tsx
  client/src/components/LayoutMypage.tsx
  client/src/components/LayoutSearch.tsx
  client/src/components/main/MainCardStyle.tsx
  client/src/pages/home/Home.tsx
  client/src/pages/home/TagList.tsx
  client/src/pages/home/Tags.tsx
Labels: 🔨 Feature, ❗️high-priority, 🖥 Frontend

#177 feature/#166 병원 디테일 정보에서 Tag 데이터 (-id -> Tag데이터내용)
  server/src/routers/HospRouter.ts
  server/src/services/HospTagService.ts
Labels: ⚙️ Backend, 🔧 enhancement, ⬇️ low-priority

#179 feature/#170: 병원 로그인 라우팅 분기
  client/package-lock.json
  client/package.json
  client/src/components/main/MainCard.tsx
  client/src/index.tsx
  client/src/pages/login/LoginLayout.tsx
  client/src/state/HospitalState.tsx
Labels: 🔨 Feature, ❗️high-priority, 🖥 Frontend

#193 feature/#191 : 로그인 라우팅 버그 해결
  client/src/pages/login/LoginLayout.tsx
Labels: 🐛 Bug, 🖥 Frontend

#182 Feature/#176 오피스아워 반영하여 기능추가
  client/src/pages/hospital-info/HospitalInfo.tsx
  client/src/pages/hospital-info/Interface.tsx
Labels: 🔨 Feature, ❗️high-priority, 🖥 Frontend

#189 feature/#185: 리뷰별점 추가
  server/src/db/models/HospModel.ts
  server/src/db/schemas/HospSchema.ts
  server/src/routers/HospRouter.ts
Labels: ⚙️ Backend, ⬇️ low-priority, 🔨 Feature

#194 feature/#192 : 병원 상세 정보 조회(병원유저)
  server/src/routers/HospRouter.ts
Labels: ⚙️ Backend, 🔨 Feature, ❗️high-priority

#195 Feature/#171 리뷰API
  server/src/app.ts
  server/src/controllers/ReviewController.ts
  server/src/routers/ReviewRouter.ts
  server/src/routers/index.ts
  server/src/services/UserService.ts
Labels: ⚙️ Backend, 🔨 Feature, ❗️high-priority

#200 feature/#198: 병원 리스트 조회(메인페이지-Tag)
  client/src/pages/hospital-info/HospitalInfo.tsx
  server/src/db/models/HospModel.ts
  server/src/db/models/HospRegStatusModel.ts
  server/src/db/models/HospStatusModel.ts
  server/src/db/models/HospTagModel.ts
  server/src/routers/HospRouter.ts
  server/src/services/HospService.ts
Labels: ⚙️ Backend, 🔨 Feature, ❗️high-priority

#203 Feature/#199 리뷰 API 라우팅 설정 완료
  server/src/controllers/ReviewController.ts
  server/src/db/models/ReviewModel.ts
  server/src/middlewares/LoginRequired.ts
  server/src/routers/PetRouter.ts
  server/src/routers/ReviewRouter.ts
  server/src/routers/UserRouter.ts
  server/src/services/ReviewService.ts
  server/src/types/express/index.d.ts
Labels: ⚙️ Backend, 🔨 Feature, ❗️high-priority

#204 feature/#184 : 내 펫 정보 보여주기
  client/src/components/detail/TimeButton.tsx
  client/src/components/main/MainData.tsx
  client/src/pages/detail/Detail.tsx
  client/src/pages/detail/PetSelect.tsx
  client/src/pages/home/TagList.tsx
  client/src/pages/home/Tags.tsx
Labels: 🔨 Feature, ❗️high-priority, 🖥 Frontend

#208 Feature/#207 관리자 병원 정보 수정 API
  server/src/db/models/HospModel.ts
  server/src/middlewares/ErrorHandler.ts
  server/src/routers/HospRouter.ts
  server/src/services/HospService.ts
Labels: ⚙️ Backend, 🔨 Feature, ❗️high-priority

#213 feature/#209: 디테일 페이지 API 적용
  client/src/App.tsx
  client/src/components/TimeButton.tsx
  client/src/components/main/MainKeyWord.tsx
  client/src/pages/detail/Detail.tsx
  client/src/pages/detail/DetailStyle.tsx
Labels: 🔨 Feature, ❗️high-priority, 🖥 Frontend

#219 Feature/#181 태그 및 홈 화면 구현
  client/package-lock.json
  client/src/App.tsx
  client/src/components/Header.tsx
  client/src/components/HeaderMypage.tsx
  client/src/components/LayoutMypage.tsx
  client/src/components/LayoutSearch.tsx
  client/src/components/Search.tsx
  client/src/components/main/MainCard.tsx
  client/src/components/main/MainCardStyle.tsx
  client/src/components/main/MainData.tsx
  client/src/pages/home/Home.tsx
  client/src/pages/home/Pagenation.tsx
  client/src/pages/home/TagList.tsx
  client/src/pages/home/Tags.tsx
  client/src/pages/register/Register.tsx
  client/src/pages/register/RegisterForm.tsx
Labels: 🔨 Feature, ❗️high-priority, 🖥 Frontend

#216 feature/#214: 일반 유저 role과 status recoil에 담기
  client/src/pages/login/LoginLayout.tsx
  client/src/state/UserState.tsx
Labels: 🔨 Feature, ❗️high-priority, 🖥 Frontend

#226 feature/#224 : 병원 서비스 적용 및 예약 시간 설정
  client/src/App.tsx
  client/src/components/detail/TimeButton.tsx
  client/src/pages/detail/Detail.tsx
  client/src/pages/detail/HospitalService.tsx
  client/src/pages/detail/PetSelect.tsx
Labels: 🔨 Feature, ❗️high-priority, 🖥 Frontend

#228 feature/#221: 마이페이지 롤에 따라 이동
  client/src/components/Header.tsx
  client/src/components/main/MainCard.tsx
  client/src/pages/home/Home.tsx
  client/src/pages/home/TagList.tsx
  client/src/pages/home/Tags.tsx
  client/src/pages/login/LoginLayout.tsx
Labels: 🔨 Feature, ❗️high-priority, 🖥 Frontend

#217 Feature/#190 관리자 전체회원 조회 검색 및 분류
  client/src/pages/admin-userlist/AdminUserList.tsx
  client/src/pages/admin-userlist/SearchBar.tsx
  client/src/pages/admin-userlist/UserCard.tsx
  client/src/pages/user-info/Interface.tsx
Labels: 🖥 Frontend

#211 Feature/#201 오피스아워 반영하여 체크박스 버튼 구현
  client/src/pages/hospital-info/HospitalInfo.tsx
  client/src/pages/hospital-info/Interface.tsx
  client/src/pages/hospital-info/Style.tsx
Labels: 🔨 Feature, ❗️high-priority, 🖥 Frontend

#215 feature/#212: 관리자 병원리스트 조회
  server/src/db/models/HospModel.ts
  server/src/routers/HospRouter.ts
  server/src/services/HospService.ts
Labels: ⚙️ Backend, 🔨 Feature, ❗️high-priority

#223 feature/#220: 병원 로그아웃
  server/src/routers/HospRouter.ts
Labels: ⚙️ Backend, 🔨 Feature, ❗️high-priority

#227 Feature/#222 회원 탈퇴
  client/src/pages/user-info/Interface.tsx
  client/src/pages/user-info/UserInfo.tsx
Labels: 🖥 Frontend

#236 Feature/#225 병원 페이지 스타일 수정
  client/src/pages/hospital-info/HospitalInfo.tsx
  client/src/pages/hospital-info/Style.tsx
Labels: ↔️ mid-priority, 🖥 Frontend

#243 feature/#242: 병원 로그인 쿠키 오류 해결
  client/src/common/CustomAxios.tsx
Labels: 🐛 Bug, ❗️high-priority, 🖥 Frontend

#241 feature/#238: 예약페이지 모달창 틀 완성
  client/src/components/ModalStyle.tsx
  client/src/components/book/ReservationContent.tsx
  client/src/components/book/ReservationModalForm.tsx
Labels: 🔨 Feature, ❗️high-priority, 🖥 Frontend

#252 feature/#250: 일반 유저 예약 리스트 조회-페이지네이션
  server/src/db/models/RezModel.ts
  server/src/routers/RezRouter.ts
  server/src/services/HospService.ts
  server/src/services/PetService.ts
  server/src/services/RezService.ts
  server/src/services/RezStatusService.ts
Labels: ⚙️ Backend, 🔨 Feature, ❗️high-priority

#249 Feature/#239 회원 내 예약 확인 페이지 틀 완성
  client/src/App.tsx
  client/src/pages/user-reserv/ReserveCard.tsx
  client/src/pages/user-reserv/ReserveStyle.tsx
  client/src/pages/user-reserv/UserReserve.tsx
Labels: 🖥 Frontend

#251 Feature/#240 기본 병원 정보 가져오기&회원 탈퇴
  client/src/components/PasswordModalStyle.tsx
  client/src/pages/hospital-info/HospitalInfo.tsx
Labels: 🔨 Feature, ❗️high-priority, 🖥 Frontend

#233 Feature/#210 에러핸들러 및 유저 관련 코드 수정
  server/src/controllers/ReviewController.ts
  server/src/controllers/UserController.ts
  server/src/controllers/Utils.ts
  server/src/db/models/UserModel.ts
  server/src/db/schemas/UserSchema.ts
  server/src/middlewares/ErrorHandler.ts
  server/src/middlewares/HospLoginRequired.ts
  server/src/middlewares/LoginRequired.ts
  server/src/routers/HospRegStatusRouter.ts
  server/src/routers/HospRouter.ts
  server/src/routers/HospStatusRouter.ts
  server/src/routers/HospTagRouter.ts
  server/src/routers/PetRouter.ts
  server/src/routers/UserRouter.ts
  server/src/services/HospRegStatusService.ts
  server/src/services/HospService.ts
  server/src/services/HospServiceService.ts
  server/src/services/HospStatusService.ts
  server/src/services/HospTagService.ts
  server/src/services/ReviewService.ts
  server/src/services/UserService.ts
  server/src/types/UserTypes.ts
Labels: ⚙️ Backend, 🔧 enhancement, 🔨 Feature, ❗️high-priority

#256 feature/#254: 에러 핸들러변경 - Error객체 던제는 에러 핸들링 생성
  server/package-lock.json
  server/package.json
  server/src/middlewares/ErrorHandler.ts
Labels: 🐛 Bug, ⚙️ Backend, 🔧 enhancement, 🔨 Feature

#259 feature/#258: 병원 내역 조회 API
  client/public/logo192.png
  client/public/logo512.png
  server/src/routers/RezRouter.ts
  server/src/services/UserService.ts
Labels: ⚙️ Backend, 🔨 Feature, ❗️high-priority

#260 feature/#257: 카카오 로그인 API 연결
  client/src/pages/login/LoginLayout.tsx
Labels: 🔨 Feature, ❗️high-priority, 🖥 Frontend

#262 feature/#261: 관리자 예약 리스트 조회API
  server/src/routers/RezRouter.ts
  server/src/services/HospService.ts
Labels: ⚙️ Backend, 🔨 Feature, ❗️high-priority

#263 feature/#261 예약 조회 리스트에서 펫 정보 삭제당했을 때 빈 값으로 펫 정보 제공
  server/src/routers/RezRouter.ts
  server/src/services/PetService.ts
Labels: 🐛 Bug, ⚙️ Backend, ❗️high-priority

#272 feature/#268: 일반유저/병원 예약 상태 변경 API
  server/src/db/models/RezModel.ts
  server/src/routers/RezRouter.ts
  server/src/services/RezService.ts
Labels: ⚙️ Backend, 🔨 Feature, ❗️high-priority

#265 Feature/#264 병원별 리뷰 평균 구하기
  server/src/app.ts
  server/src/controllers/ReviewController.ts
  server/src/db/models/HospModel.ts
  server/src/db/models/ReviewModel.ts
  server/src/db/schemas/ReviewSchema.ts
  server/src/passport/KakaoStrategy.ts
  server/src/routers/ReviewRouter.ts
  server/src/services/ReviewService.ts
  server/src/types/ReviewTypes.ts
Labels: ⚙️ Backend, 🔨 Feature, ↔️ mid-priority

#274 feature/#271 : 로그인 버그 해결
  client/src/pages/login/LoginLayout.tsx
  client/src/state/UserState.tsx
Labels: 🐛 Bug, ❗️high-priority, 🖥 Frontend

#279 Feature/#273: ReadMe 작성 및 RefreshToken 시간 설정 수정
  README.md
  server/src/middlewares/HospLoginRequired.ts
  server/src/services/HospService.ts
Labels: 🔧 enhancement, 📖 Document

#281 Feature/#280 관리자의 회원상태 변경 api
  server/index.ts
  server/package.json
  server/src/controllers/ReviewController.ts
  server/src/controllers/UserController.ts
  server/src/db/models/UserModel.ts
  server/src/routers/UserRouter.ts
  server/src/services/UserService.ts
  server/src/types/UserTypes.ts
Labels: ⚙️ Backend, 🔨 Feature, ❗️high-priority

#284 Feature/#283 펫 정보 수정 삭제 추가
  client/src/App.tsx
  client/src/pages/pet-info/PetInfo.tsx
  client/src/pages/pet-information/AddPet.tsx
  client/src/pages/pet-information/PetCard.tsx
  client/src/pages/pet-information/PetInfoInterface.tsx
  client/src/pages/pet-information/PetInfoStyle.tsx
  client/src/pages/pet-information/PetInformation.tsx
  server/src/app.ts
Labels: 🖥 Frontend

#285 feature/#275: 디테일 예약하기 POST 요청
  client/src/components/TimeButton.tsx
  client/src/components/detail/TimeButton.tsx
  client/src/pages/detail/Calendar.tsx
  client/src/pages/detail/Detail.tsx
  client/src/pages/detail/HospitalService.tsx
  client/src/pages/detail/PetSelect.tsx
  client/src/state/ReservationState.tsx
Labels: 🔨 Feature, ❗️high-priority, 🖥 Frontend

#278 Feature/#269 병원 정보 기능 오류 수정
  client/src/pages/hospital-info/HospitalInfo.tsx
  client/src/pages/hospital-info/Interface.tsx
Labels: 🔨 Feature, ❗️high-priority, 🖥 Frontend

#289 feature/#287: 예약리스트 조회 데이터가 없을 시 error생성 제거
  server/src/services/RezService.ts
Labels: ⚙️ Backend

#290 Feature/#266 회원 내 예약 페이지 구현
  client/package-lock.json
  client/package.json
  client/src/components/book/ReservationModalForm.tsx
  client/src/pages/admin-userlist/AdminUserList.tsx
  client/src/pages/admin-userlist/UserCard.tsx
  client/src/pages/detail/Calendar.tsx
  client/src/pages/detail/HospitalService.tsx
  client/src/pages/user-info/UserInfo.tsx
  client/src/pages/user-reserv/ReserveCard.tsx
  client/src/pages/user-reserv/UserReserve.tsx
Labels: 🖥 Frontend

#293 Feature/#292 : 펫 정보 추가 사진 기능 수정 및 구현
  client/src/pages/pet-information/AddPet.tsx
  client/src/pages/pet-information/PetInformation.tsx
  server/src/routers/PetRouter.ts
Labels: 🐛 Bug, ⚙️ Backend, 🔧 enhancement, ❗️high-priority, 🖥 Frontend

#295 feature/#294 펫 수정 기능 완료
  client/public/defaultImg.png
  client/src/pages/pet-information/AddPet.tsx
  client/src/pages/pet-information/PetCard.tsx
  client/src/pages/pet-information/PetInfoStyle.tsx
  client/src/pages/pet-information/PetInformation.tsx
Labels: 🖥 Frontend

#297 Feature/#296 병원 페이지 주석, 콘솔 정리
  client/src/pages/hospital-info/HospitalInfo.tsx
Labels: ↔️ mid-priority, 🖥 Frontend

#301 Feature/#277 헤더 오류 & 태그 오류 수정
  client/src/components/Header.tsx
  client/src/pages/home/Tags.tsx
  client/src/pages/hospital-reserve/ReserveCard.tsx
  client/src/pages/login/LoginLayout.tsx
Labels: 🐛 Bug, ❗️high-priority, 🖥 Frontend

#305 Feature/#304 수정 머지
  client/src/components/Header.tsx
  client/src/components/InfoForm.tsx
  client/src/components/book/ResModal.tsx
  client/src/components/detail/TimeButton.tsx
  client/src/components/main/MainCardStyle.tsx
  client/src/components/main/MainKeyWordStyle.tsx
  client/src/pages/admin-mypage/AdminMypage.tsx
  client/src/pages/admin-userlist/AdminUserList.tsx
  client/src/pages/admin-userlist/UserCard.tsx
  client/src/pages/detail/Calendar.tsx
  client/src/pages/detail/Detail.tsx
  client/src/pages/detail/DetailStyle.tsx
  client/src/pages/hospital-mypage/HospitalMypage.tsx
  client/src/pages/pet-information/PetCard.tsx
  client/src/pages/pet-information/PetInfoStyle.tsx
  client/src/pages/user-info/UserInfo.tsx
  client/src/pages/user-mypage/UserMypage.tsx
  client/src/pages/user-reserv/ReserveCard.tsx
  client/src/pages/user-reserv/UserReserve.tsx
Labels: 🖥 Frontend

#309 feature/#307 병원 페이지 요소 추가,주석삭제
  client/src/pages/hospital-info/HospitalInfo.tsx
Labels: ↔️ mid-priority, 🖥 Frontend

#322 Feature/#318 렌더링 및 불필요한 console, alert 제거
  client/public/defaultImg.png
  client/src/components/book/ResModal.tsx
  client/src/pages/admin-userlist/AdminUserList.tsx
  client/src/pages/admin-userlist/UserCard.tsx
  client/src/pages/pet-information/PetCard.tsx
  client/src/pages/pet-information/PetInformation.tsx
  client/src/pages/user-info/UserInfo.tsx
  client/src/pages/user-reserv/ReserveCard.tsx
  client/src/pages/user-reserv/UserReserve.tsx
Labels: 🖥 Frontend

#314 feature/#313: axios 모듈화 및 login 코치님 피드백 적용
  client/src/App.tsx
  client/src/pages/login/Login.tsx
  client/src/utils/.gitkeep
  client/src/utils/AxiosModule.tsx
Labels: 🔧 enhancement, 🔨 Feature, ❗️high-priority

#316 feature/#315: 디테일 페이지 서비스 가격 숫자 표기 방식 변경
  client/src/pages/detail/Detail.tsx
  client/src/pages/detail/HospitalService.tsx
Labels: 🔧 enhancement, ❗️high-priority, 🖥 Frontend

#332 Feature/#280 관리자의 회원 상태 변경 api
  server/src/controllers/UserController.ts
  server/src/db/models/UserModel.ts
  server/src/passport/KakaoStrategy.ts
  server/src/passport/LocalStrategy.ts
  server/src/routers/UserRouter.ts
  server/src/services/UserService.ts
Labels: ⚙️ Backend, 🔨 Feature

#321 feature/#319 : ESLint , Prettier 설정
  client/.eslintrc.json
  client/.prettierrc
  client/package-lock.json
  client/package.json
Labels: 🔨 Feature, ❗️high-priority, 🖥 Frontend

#335 Feature/#327: 병원 정보 페이지 상수 컴포넌트 분리
  client/src/pages/hospital-info/Constants.tsx
  client/src/pages/hospital-info/HospitalInfo.tsx
Labels: 🛠 Refactor, ↔️ mid-priority, 🖥 Frontend

#334 Feature/#323 [FE] 관리자 유저 상태변경 및 ui 수정
  client/src/pages/admin-userlist/UserCard.tsx
  client/src/pages/user-info/UserInfo.tsx
Labels: 🖥 Frontend

#337 Feature#336 오류 해결
  .vscode/settings.json
  client/.prettierrc
  client/src/pages/hospital-info/Constants.tsx
  client/src/pages/hospital-info/HospitalInfo.tsx
  client/src/pages/hospital-info/Interface.tsx
  client/src/pages/login/Login.tsx
  server/src/app.ts
Labels: 🐛 Bug, ❗️high-priority, 🖥 Frontend

#344 [#343]fix : 회원정보수정 에러 해결
  server/src/controllers/UserController.ts
Labels: 🐛 Bug, ⚙️ Backend

#342 Feature/#338 페이지네이션, 상태취소
  client/public/mainDefaultImg.jpg
  client/public/mainDefaultImg.png
  client/src/common/CustomAxios.tsx
  client/src/components/Buttons/RadioBtn.tsx
  client/src/components/book/ResModal.tsx
  client/src/components/main/MainCard.tsx
  client/src/pages/admin-userlist/AdminUserList.tsx
  client/src/pages/admin-userlist/UserCard.tsx
  client/src/pages/detail/Detail.tsx
  client/src/pages/home/Tags.tsx
  client/src/pages/pet-information/AddPet.tsx
  client/src/pages/pet-information/PetCard.tsx
  client/src/pages/pet-information/PetInfoStyle.tsx
  client/src/pages/pet-information/PetInformation.tsx
  client/src/pages/user-info/UserInfo.tsx
  client/src/pages/user-reserv/ReserveCard.tsx
  client/src/pages/user-reserv/UserReserve.tsx
Labels: 🖥 Frontend
